---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
domains: []
reporters:
  - standardrb
  - require_not_found
  - typecheck:typed
require:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
require_paths: []
plugins:
  - solargraph-rails
  - solargraph-standardrb
max_files: 5000
